// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalLoadBalancer) DeepCopyInto(out *GlobalLoadBalancer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalLoadBalancer.
func (in *GlobalLoadBalancer) DeepCopy() *GlobalLoadBalancer {
	if in == nil {
		return nil
	}
	out := new(GlobalLoadBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GlobalLoadBalancer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalLoadBalancerList) DeepCopyInto(out *GlobalLoadBalancerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GlobalLoadBalancer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalLoadBalancerList.
func (in *GlobalLoadBalancerList) DeepCopy() *GlobalLoadBalancerList {
	if in == nil {
		return nil
	}
	out := new(GlobalLoadBalancerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GlobalLoadBalancerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalLoadBalancerSpec) DeepCopyInto(out *GlobalLoadBalancerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalLoadBalancerSpec.
func (in *GlobalLoadBalancerSpec) DeepCopy() *GlobalLoadBalancerSpec {
	if in == nil {
		return nil
	}
	out := new(GlobalLoadBalancerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalLoadBalancerStatus) DeepCopyInto(out *GlobalLoadBalancerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalLoadBalancerStatus.
func (in *GlobalLoadBalancerStatus) DeepCopy() *GlobalLoadBalancerStatus {
	if in == nil {
		return nil
	}
	out := new(GlobalLoadBalancerStatus)
	in.DeepCopyInto(out)
	return out
}
